// Public research summaries. Keep findings, limitations and our interpretation separate.
// Source locators support future editorial checks; they are not efficacy claims for Lernbus.
export default {
  reviewed: '2026-09-25',
  sources: {
    skene: { author: 'Skene et al.', year: '2022', title: 'Can guidance during play enhance children’s learning and development in educational contexts?', url: 'https://doi.org/10.1111/cdev.13730', locator: 'Abstract; Results; Conclusion' },
    dowdall: { author: 'Dowdall et al.', year: '2020', title: 'Shared Picture Book Reading Interventions for Child Language Development', url: 'https://pubmed.ncbi.nlm.nih.gov/30737957/', locator: 'Abstract (19 randomised trials)' },
    noble: { author: 'Noble et al.', year: '2019', title: 'The impact of shared book reading on children’s language skills', url: 'https://doi.org/10.1016/j.edurev.2019.100290', locator: 'Abstract; active controls and follow-up analyses' },
    emslander: { author: 'Emslander et al.', year: '2025', title: 'Teacher-student relationships and student outcomes', url: 'https://pubmed.ncbi.nlm.nih.gov/39928458/', locator: 'Abstract (26 meta-analyses; associations)' },
    nickow: { author: 'Nickow, Oreopoulos & Quan', year: '2024', title: 'The Promise of Tutoring for PreK–12 Learning', url: 'https://doi.org/10.3102/00028312231208687', locator: 'Published abstract; pooled effect 0.288 SD; programme moderators' },
    best: { author: 'McKean et al.', year: '2025', title: 'A Cluster Randomized Controlled Trial Comparing the Efficacy of Pre-School Language Interventions', url: 'https://doi.org/10.1111/1460-6984.70036', locator: 'Abstract; sections 2.2–2.5, 3.3 and 4; active comparator A-DLS' },
    neli: { author: 'Roy et al. / NFER', year: '2026', title: 'Effectiveness Trial of Nuffield Early Language Intervention – Preschool', url: 'https://www.nfer.ac.uk/publications/effectiveness-trial-of-nuffield-early-language-intervention-preschool/', locator: '15 July 2026; trial overview and Key Findings' },
    neliReport: { author: 'Education Endowment Foundation', year: '2026', title: 'NELI Preschool: evaluation and reports', url: 'https://educationendowmentfoundation.org.uk/projects-and-evaluation/projects/neli-preschool-2023-24-trial', locator: 'Evaluation report pp. 5–6: randomisation, planned dosage, 0.10 SD (95% CI 0.02–0.18), limits of targeted-component comparison' },
    roots: { author: 'Clarke et al.', year: '2017', title: 'Testing the Efficacy of a Kindergarten Mathematics Intervention by Small Group Size', url: 'https://files.eric.ed.gov/fulltext/ED578431.pdf', locator: 'pp. 4–5 (delivery), p. 11 (outcomes and group-size comparison)', pdf: true },
    basel: { author: 'Universität Basel / Marina Jambreus', year: '2025', title: 'Prüfung der Wirksamkeit früher Deutschförderung, Kanton Basel-Stadt', url: 'https://media.bs.ch/original_file/10090193b139bd4ca3282d31b876c19c734680cc/260305-fruehe-deutschfoerderung-abschlussbericht.pdf', locator: '7 July 2025, released March 2026; pp. 3–4, 7–9, 12–15', pdf: true },
    kompas: { author: 'Sammann et al. / HfH', year: '2026', title: 'KOMPAS – Kommunikative Partizipation und Sprachförderung bei Kindern mit DaZ', url: 'https://www.hfh.ch/projekt/kompas-kommunikative-partizipation-und-sprachfoerderung-bei-kindern-mit-daz', locator: 'Methode and Ergebnisse: KOMPAS 2 (randomised), not KOMPAS 1' }
  },
  studies: [
    {
      id: 'spiel', sources: ['skene'],
      de: { topic: 'Spiel & Mathematik', title: 'Entdecken, mit passenden Impulsen.', studied: 'Eine Übersicht untersuchte 39 Studien mit Kindern von etwa 1 bis 8 Jahren. Beim angeleiteten Spiel erkunden Kinder selbst; Erwachsene geben Impulse und verfolgen ein Lernziel.', finding: 'Für frühe Mathematik und Formenwissen fanden sich Vorteile gegenüber direkter Anleitung. Für Lesen sowie soziale und emotionale Entwicklung zeigte sich keine allgemeine Überlegenheit. Viele Einzelbefunde beruhen auf wenigen Studien.', meaning: 'Das passt zu unserem Ansatz, Spiel mit gezielten Fragen und Aufgaben zu verbinden. Es belegt keine Wirkung auf alle Entwicklungsbereiche.' },
      en: { topic: 'Play & maths', title: 'Exploring, with thoughtful guidance.', studied: 'A review examined 39 studies of children aged about 1–8. In guided play, children explore while adults offer prompts and work towards a learning goal.', finding: 'Early maths and shape knowledge benefited compared with direct instruction. There was no general advantage for literacy or social and emotional development. Many findings relied on few studies.', meaning: 'This supports combining play with purposeful questions and tasks. It does not establish benefits across every area of development.' }
    },
    {
      id: 'lesen', sources: ['dowdall', 'noble'],
      de: { topic: 'Bücher & Sprache', title: 'Über Geschichten ins Gespräch kommen.', studied: 'Dowdall und sein Team fassten 19 zufällig zugeteilte Vergleichsstudien mit Kindern von 1 bis 6 Jahren zusammen. Eltern lernten, Bilderbücher gemeinsam mit ihrem Kind zu betrachten und zu besprechen.', finding: 'Gegenüber den Vergleichsgruppen machten die Kinder im Durchschnitt grössere Fortschritte beim Sprechen und Sprachverstehen. Eine weitere Übersicht von Noble fand kleinere Effekte; gegenüber anderen Förderaktivitäten und bei späteren Messungen war kein verlässlicher Vorteil nachweisbar.', meaning: 'Geschichten bieten einen guten Anlass für Gespräche. Entscheidend ist auch, wie Erwachsene Kinder beteiligen. Diese Elternprogramme sind kein direkter Test unserer Lektionen.' },
      en: { topic: 'Books & language', title: 'Turning stories into conversations.', studied: 'Dowdall and colleagues combined 19 randomised trials with children aged 1–6. Parents learnt to share and discuss picture books with their child.', finding: 'Compared with control groups, children made greater gains in speaking and language comprehension on average. A separate review by Noble found smaller effects, with no reliable advantage over other support activities or at later assessments.', meaning: 'Stories offer opportunities for conversation. How adults involve children matters too. These parent programmes do not directly test our lessons.' }
    },
    {
      id: 'beziehung', sources: ['emslander'],
      de: { topic: 'Beziehung & Lernen', title: 'Gute Beziehungen gehören dazu.', studied: 'Eine Übersicht bündelte 26 Forschungsübersichten zu Beziehungen zwischen Lehrpersonen und Kindern vom Vorschulalter bis zum Schulabschluss.', finding: 'Gute Beziehungen hingen mit besseren Lernleistungen, mehr Motivation und höherem Wohlbefinden zusammen. Solche Zusammenhänge zeigen nicht, dass die Beziehung allein diese Unterschiede verursacht.', meaning: 'Verlässliche Begleitung ist uns wichtig. Sie ergänzt passende Lernangebote. Die Studie belegt weder einen Vorteil von Einzelstunden noch eine bestimmte Dauer des Beziehungsaufbaus.' },
      en: { topic: 'Relationships & learning', title: 'Supportive relationships matter.', studied: 'A review brought together 26 meta-analyses of teacher–student relationships from preschool through the end of school.', finding: 'Positive relationships were associated with stronger achievement, motivation and wellbeing. These associations do not show that relationships alone caused those differences.', meaning: 'We value consistent support alongside suitable learning activities. The review establishes neither an advantage for individual lessons nor a required length of time to build trust.' }
    },
    {
      id: 'foerderung', sources: ['nickow'],
      de: { topic: 'Gezielte Lernunterstützung', title: 'Förderung kann das Lernen voranbringen.', studied: 'Eine grosse Übersicht fasste zufällig zugeteilte Vergleichsstudien zu Einzel- und Kleingruppenförderung vom Vorschulalter bis zum Schulabschluss zusammen.', finding: 'Im Durchschnitt verbesserten sich die Lernleistungen. Grössere Effekte zeigten sich häufig bei jüngeren Kindern, qualifizierten Begleitpersonen und Angeboten an mindestens drei Tagen pro Woche während der Schulzeit.', meaning: 'Das spricht für gut angeleitete, gezielte Unterstützung. Die Programme unterschieden sich aber in vielen Punkten. Daraus folgt weder eine Mindesthäufigkeit noch eine erwartbare Wirkung unserer wöchentlichen Stunde.' },
      en: { topic: 'Targeted learning support', title: 'Tutoring can help learning progress.', studied: 'A large review combined randomised trials of individual and small-group tutoring from preschool through the end of school.', finding: 'Learning improved on average. Effects tended to be larger with younger children, trained teachers or assistants, and programmes held at least three days a week during school.', meaning: 'This supports well-guided, targeted help. Programmes differed in many ways, so these comparisons establish neither a minimum frequency nor an expected effect for our weekly hour.' }
    },
    {
      id: 'kurze-einheiten', sources: ['best'],
      de: { topic: 'Zeit & Häufigkeit', title: 'Auch kurze Einheiten können helfen.', studied: 'BEST wurde mit einem anderen Sprachprogramm verglichen: 102 einsprachig englischsprachige Kinder von rund 3½ bis 4½ Jahren mit schwachen Sprachleistungen. Logopädische Fachpersonen arbeiteten acht Wochen lang zweimal wöchentlich je 15 Minuten in Kleingruppen.', finding: 'BEST führte zu grösseren Fortschritten beim Sprechen. Beim Sprachverstehen gab es direkt danach und bei der Nachmessung keinen gesicherten Unterschied zwischen den Programmen.', meaning: 'Ein klar umrissenes Lernziel kann auch mit wenig Wochenzeit unterstützt werden. Untersucht wurde spezialisierte englische Sprachförderung, keine allgemeine oder deutschsprachige Frühförderung.' },
      en: { topic: 'Time & frequency', title: 'Short sessions can help too.', studied: 'BEST was compared with another language programme in 102 monolingual English-speaking children aged about 3½–4½ with weak language skills. Speech and language therapists delivered small-group sessions twice a week for eight weeks, lasting 15 minutes each.', finding: 'BEST produced greater expressive-language gains. There was no clear difference in comprehension between programmes immediately afterwards or at follow-up.', meaning: 'A focused learning goal can benefit from limited weekly time. This was specialist English-language support, not general early learning or German-language provision.' }
    },
    {
      id: 'neli', sources: ['neli', 'neliReport'],
      de: { topic: 'Sprachförderung im Alltag', title: 'Regelmässig lesen, erzählen und üben.', studied: 'Die unabhängige NELI-Preschool-Studie von 2026 umfasste 3298 Kinder von 3 bis 4 Jahren in 303 englischen Einrichtungen. Die Einrichtungen wurden zufällig zugeteilt. Das Programm sah über 20 Wochen täglich 15–20 Minuten gemeinsame Sprachaktivitäten vor, bei schwächeren Sprachkenntnissen zusätzlich dreimal 10–15 Minuten in Kleingruppen und einmal 5–10 Minuten einzeln pro Woche.', finding: 'Gegenüber dem üblichen Angebot zeigte sich ein kleiner, statistisch gesicherter Vorteil in der mündlichen Sprache. Langfristige Ergebnisse stehen noch aus.', meaning: 'Der Befund stützt strukturierte Sprachaktivitäten. Geprüft wurde das Gesamtpaket einschliesslich digitaler Materialien. Er beweist weder den Zusatznutzen der Einzelstunden noch die Wirkung unseres bildschirmfreien Formats.' },
      en: { topic: 'Language in everyday learning', title: 'Reading, talking and practising regularly.', studied: 'The independent 2026 NELI Preschool trial included 3,298 children aged 3–4 in 303 English settings. Settings were randomly assigned. The planned 20-week programme comprised daily 15–20-minute language activities, with three 10–15-minute small-group sessions and one 5–10-minute individual session each week for children with weaker language.', finding: 'Oral language improved by a small, statistically reliable amount compared with usual provision. Long-term findings are still pending.', meaning: 'This supports structured language activities. The whole package was tested, including digital materials. It establishes neither the added benefit of individual sessions nor the effect of our screen-free format.' }
    },
    {
      id: 'gruppen', sources: ['roots'],
      de: { topic: 'Gruppengrösse', title: 'Kleiner ist nicht automatisch besser.', studied: 'Bei ROOTS wurden US-Kindergartenkinder mit schwachen Mathematikleistungen zufällig Zweiergruppen, Fünfergruppen oder dem üblichen Unterricht zugeteilt. Die Förderung umfasste 50 zusätzliche Einheiten: je 20 Minuten an fünf Tagen pro Woche.', finding: 'Bei drei von sechs untersuchten Ergebnissen half die Förderung nachweisbar. Ein Lernvorteil der Zweier- gegenüber den Fünfergruppen liess sich nicht nachweisen.', meaning: 'Kleine Gruppen können sinnvoll sein. Diese Studie beweist aber weder die Gleichwertigkeit aller Gruppengrössen noch, dass zuerst ein Semester einzeln und danach zu zweit gelernt werden sollte.' },
      en: { topic: 'Group size', title: 'Smaller is not automatically better.', studied: 'ROOTS randomly assigned US kindergarten children with weak maths skills to groups of two, groups of five or usual teaching. Support comprised 50 additional sessions: 20 minutes each, five days a week.', finding: 'The intervention improved three of six measured outcomes significantly. No achievement advantage was detected for pairs over groups of five.', meaning: 'Small groups can be useful. This study proves neither that all group sizes are equivalent nor that children should spend a semester learning individually before moving to pairs.' }
    },
    {
      id: 'schweiz', sources: ['basel', 'kompas'],
      de: { topic: 'Forschung aus der Schweiz', title: 'Auf das konkrete Angebot kommt es an.', studied: 'Die Universität Basel untersuchte frühe Deutschförderung vor dem Kindergarten in den Jahren 2022/23 und 2023/24, damals mit fünf Stunden pro Woche. Ein gesondertes Schweizer Projekt, KOMPAS 2, prüfte zusätzliche SPRINT-Förderung im Kindergarten.', finding: 'Die Basler Analyse fand Vorteile besonders bei geringen Anfangskenntnissen. Sie nutzte die Grenze zur verpflichtenden Förderung für den Vergleich statt einer Auslosung; nur eine freiwillige Teilgruppe wurde direkt getestet. Im zufällig zugeteilten KOMPAS-2-Vergleich brachte SPRINT keinen nachgewiesenen Zusatznutzen gegenüber der üblichen Deutschförderung.', meaning: 'Lokale Forschung ist wertvoll. Sie zeigt zugleich: Mehr Förderung hilft nicht automatisch mehr. Beide Programme unterscheiden sich deutlich von Lernbus.' },
      en: { topic: 'Swiss research', title: 'The specific programme matters.', studied: 'The University of Basel studied German-language support before kindergarten in 2022/23 and 2023/24, then offered for five hours a week. A separate Swiss project, KOMPAS 2, tested additional SPRINT support in kindergarten.', finding: 'The Basel analysis found benefits especially for children with low starting skills. It used the assignment threshold rather than randomisation; direct testing involved a volunteer subsample. In the randomised KOMPAS 2 comparison, SPRINT brought no demonstrated additional benefit over usual German-language support.', meaning: 'Local research is valuable. It also shows that adding support does not automatically add benefit. Both programmes differ substantially from Lernbus.' }
    }
  ]
};
